// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Apr 25 16:13:30 2019

ADS8688 ADS8688_inst
(
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.CLK_50M(CLK_50M_sig) ,	// input  CLK_50M_sig
	.clk_263(clk_263_sig) ,	// input  clk_263_sig
	.CS(CS_sig) ,	// output  CS_sig
	.SCLK(SCLK_sig) ,	// output  SCLK_sig
	.SDI(SDI_sig) ,	// output  SDI_sig
	.SDO(SDO_sig) ,	// input  SDO_sig
	.RST(RST_sig) ,	// output  RST_sig
	.rddat0(rddat0_sig) ,	// output [15:0] rddat0_sig
	.rddat1(rddat1_sig) ,	// output [15:0] rddat1_sig
	.rddat2(rddat2_sig) ,	// output [15:0] rddat2_sig
	.outRMS(outRMS_sig) ,	// output [15:0] outRMS_sig
	.dataAddr(dataAddr_sig) ,	// input [11:0] dataAddr_sig
	.RDdata(RDdata_sig) 	// input  RDdata_sig
);

