// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Apr 18 19:47:02 2019

KEY KEY_inst
(
	.clk_400M(clk_400M_sig) ,	// input  clk_400M_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.rddat(rddat_sig) ,	// output [7:0] rddat_sig
	.irq(irq_sig) ,	// output  irq_sig
	.cs(cs_sig) ,	// input  cs_sig
	.KEY_H(KEY_H_sig) ,	// inout [3:0] KEY_H_sig
	.KEY_V(KEY_V_sig) 	// inout [3:0] KEY_V_sig
);

